version: '3.7'

services:
  api:
    build:
      dockerfile: ./Dockerfile
      target: dev
    image: markus-autotest-api-dev:1.0.0
    container_name: 'autotest-api'
    volumes:
      - .:/app:cached
    environment:
      - REDIS_URL=redis://redis:6379/
      - FLASK_HOST=0.0.0.0
    ports:
      - '5000:5000'
    depends_on:
      - redis
    networks:
      - default
      - markus_dev

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_autotest:/data
    ports:
      - 6379

  rq_dashboard:
    image: eoranged/rq-dashboard
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/
    ports:
      - '9181:9181'
    depends_on:
      - redis

volumes:
  redis_autotest:

networks:
  markus_dev:
    name: markus_dev
